version: '3'

services:
  ravendb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "38888:38888"
    environment:
      - RAVEN_License=${RAVEN_License}
    volumes:
      - ./db-storage:/var/lib/ravendb/data/Databases