version: '3'

services:
  ravendb:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    ports:
      - "8080:8080"
      - "38888:38888"
    environment:
      - RAVEN_License=${RAVEN_License}
    volumes:
      - ./db-storage:/var/lib/ravendb/data/Databases
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7024:7024"
      - "5100:5100"
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5174:5174"

