/**
 * A list of the most popular books to suggest to the user
 */
export const mostPopular100Books: string[] = [
  "To Kill a Mockingbird",
  "1984",
  "Harry Potter and the Sorcerer's Stone",
  "The Lord of the Rings",
  "The Great Gatsby",
  "Pride and Prejudice",
  "The Catcher in the Rye",
  "The Hobbit",
  "Fahrenheit 451",
  "Jane Eyre",
  "Animal Farm",
  "Gone with the Wind",
  "The Book Thief",
  "The Chronicles of Narnia",
  "The Kite Runner",
  "The Hunger Games",
  "The Da Vinci Code",
  "The Alchemist",
  "The Help",
  "The Girl with the Dragon Tattoo",
  "The Fault in Our Stars",
  "The Handmaid's Tale",
  "The Little Prince",
  "Life of Pi",
  "The Shining",
  "Memoirs of a Geisha",
  "The Secret Garden",
  "The Adventures of Sherlock Holmes",
  "The Giver",
  "The Outsiders",
  "The Picture of Dorian Gray",
  "The Count of Monte Cristo",
  "Brave New World",
  "Wuthering Heights",
  "The Odyssey",
  "The Iliad",
  "Les Misérables",
  "Moby-Dick",
  "War and Peace",
  "Crime and Punishment",
  "The Brothers Karamazov",
  "Anna Karenina",
  "Madame Bovary",
  "The Divine Comedy",
  "The Canterbury Tales",
  "Don Quixote",
  "One Hundred Years of Solitude",
  "Love in the Time of Cholera",
  "Beloved",
  "Invisible Man",
  "Things Fall Apart",
  "The Stranger",
  "The Road",
  "The Sun Also Rises",
  "A Farewell to Arms",
  "For Whom the Bell Tolls",
  "Catch-22",
  "Slaughterhouse-Five",
  "The Grapes of Wrath",
  "East of Eden",
  "Of Mice and Men",
  "The Old Man and the Sea",
  "The Call of the Wild",
  "White Fang",
  "The Jungle Book",
  "The Wind in the Willows",
  "Peter Pan",
  "Alice's Adventures in Wonderland",
  "Through the Looking-Glass",
  "Charlotte's Web",
  "Matilda",
  "Charlie and the Chocolate Factory",
  "James and the Giant Peach",
  "The BFG",
  "The Witches",
  "The Twits",
  "Fantastic Mr. Fox",
  "The Tale of Peter Rabbit",
  "Winnie-the-Pooh",
  "The Very Hungry Caterpillar",
  "Goodnight Moon",
  "Where the Wild Things Are",
  "The Cat in the Hat",
  "Green Eggs and Ham",
  "Oh, the Places You'll Go!",
  "The Lorax",
  "Horton Hears a Who!",
  "How the Grinch Stole Christmas!",
  "The Giving Tree",
  "Where the Sidewalk Ends",
  "A Light in the Attic",
  "Falling Up",
  "The Polar Express",
  "The Velveteen Rabbit",
  "The Secret Life of Bees",
  "The Lovely Bones",
  "The Time Traveler's Wife",
  "Water for Elephants",
  "The Night Circus",
  "The Goldfinch",
];
